sudo: false
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
    - main
install:
  - npm ci
  # keep the npm cache around to speed up installs
script:
  - npm run test